MODULE IONOBG
 USE GEOAXES
 USE SYSINFO
 USE SYSGRIDS
 USE INTERPSUBS

 INTERFACE GEOBFIELD
   MODULE PROCEDURE R8GEOBFIELD,R4GEOBFIELD
 END INTERFACE GEOBFIELD

 INTERFACE CDBFIELD
   MODULE PROCEDURE R8CDBFIELD,R4CDBFIELD
 END INTERFACE CDBFIELD

 INTERFACE EDBFIELD
   MODULE PROCEDURE R8EDBFIELD,R4EDBFIELD
 END INTERFACE EDBFIELD


!!SYSTEM SWITCHES
  LOGICAL             :: EMPIRICAL=.TRUE.
  LOGICAL             :: TIEGCM   =.FALSE.
  LOGICAL             :: SAMI3    =.FALSE.
  LOGICAL             :: GITM     =.FALSE.
  LOGICAL             :: CTIPe    =.FALSE.

!!SYSTEM PARAMETERS
  LOGICAL             :: IonoNe      = .TRUE.
  LOGICAL             :: IonoNi      = .FALSE.
  LOGICAL             :: IonoNiS     = .FALSE.
  LOGICAL             :: IonoNn      = .FALSE.
  LOGICAL             :: IonoNnS     = .FALSE.
  LOGICAL             :: IonoTe      = .TRUE.
  LOGICAL             :: IonoTi      = .TRUE.
  LOGICAL             :: IonoTiS     = .FALSE.
  LOGICAL             :: IonoTn      = .FALSE.
  LOGICAL             :: IonoTnS     = .FALSE.
  LOGICAL             :: IonoBabs    = .TRUE.
  LOGICAL             :: IonoBr      = .FALSE.
  LOGICAL             :: IonoBphi    = .FALSE.
  LOGICAL             :: IonoBtheta  = .FALSE.
  LOGICAL             :: IonoVzonal  = .FALSE.
  LOGICAL             :: IonoVmerid  = .FALSE.
  LOGICAL             :: IonoEPOTEN  = .FALSE.
  LOGICAL             :: IonoEFIELD  = .FALSE.
  LOGICAL             :: IonoOMEGAce = .TRUE.
  LOGICAL             :: IonoOMEGAci = .TRUE.
  LOGICAL             :: IonoOMEGAciS= .FALSE.
  LOGICAL             :: IonoNUen    = .TRUE.
  LOGICAL             :: IonoNUenS   = .FALSE.
  LOGICAL             :: IonoNUin    = .TRUE.
  LOGICAL             :: IonoNUinS   = .FALSE.
  LOGICAL             :: IonoNUei    = .FALSE.
  LOGICAL             :: IonoNUeiS   = .FALSE.
  LOGICAL             :: IonoOMEGApi = .FALSE.
  LOGICAL             :: IonoOMEGApiS= .FALSE.
  LOGICAL             :: IonoOMEGApe = .FALSE.
  LOGICAL             :: IonoRHOi    = .TRUE.
  LOGICAL             :: IonoRHOiS   = .FALSE.
  LOGICAL             :: IonoRHOe    = .TRUE.
  LOGICAL             :: IonoCs      = .TRUE.
  LOGICAL             :: IonoCsS     = .FALSE.
  LOGICAL             :: IonoLne     = .TRUE.
  LOGICAL             :: IonoVthi    = .TRUE.
  LOGICAL             :: IonoVthiS   = .FALSE.
  LOGICAL             :: IonoVthe    = .TRUE.
  LOGICAL             :: IonoVion    = .FALSE.
  LOGICAL             :: IonoVionS   = .FALSE.
  LOGICAL             :: IonoVexb    = .TRUE.
  LOGICAL             :: IonoVAlfven = .FALSE.
  LOGICAL             :: IonoVAlfvenS= .FALSE.
  LOGICAL             :: IonoLAMBDAD = .FALSE.
  LOGICAL             :: IonoMUeH    = .FALSE.
  LOGICAL             :: IonoMUiH    = .FALSE.
  LOGICAL             :: IonoMUiHS   = .FALSE.
  LOGICAL             :: IonoMUeP    = .FALSE.
  LOGICAL             :: IonoMUiP    = .FALSE.
  LOGICAL             :: IonoMUiPS   = .FALSE.
  LOGICAL             :: IonoDeH     = .FALSE.
  LOGICAL             :: IonoDiH     = .FALSE.
  LOGICAL             :: IonoDiHS    = .FALSE.
  LOGICAL             :: IonoDeP     = .FALSE.
  LOGICAL             :: IonoDiP     = .FALSE.
  LOGICAL             :: IonoDiPS    = .FALSE.
  LOGICAL             :: IonoSigmaH  = .FALSE.
  LOGICAL             :: IonoSigmaHS = .FALSE.
  LOGICAL             :: IonoSigmaP  = .FALSE.
  LOGICAL             :: IonoSigmaPS = .FALSE.
  LOGICAL             :: IonoSigmao  = .FALSE.
  LOGICAL             :: IonoSigmaoS = .FALSE.

! SPECIES DETAILS
 INTEGER(4),PARAMETER :: NionS=7,NneutralS=7
 INTEGER(4),PARAMETER :: iH1p=1,iHe1p=2,iN1p=3,iO1p=4,iN21p=5
 INTEGER(4),PARAMETER :: iNO1p=6,iO21p=7
 INTEGER(4),PARAMETER :: aH=1,aHe=2,aN=3,aO=4,aN2=5,aNO=6,aO2=7
 REAL(4),   PARAMETER :: Qe=1.6022E-19,Qp=1.6022E-19
 REAL(4),   PARAMETER :: Me=9.1094E-31,Mp=1.6726E-27
 REAL(4),   PARAMETER :: Cpve=1.0
 REAL(4),   PARAMETER :: Cpvi=1.0
 REAL(4),   PARAMETER :: iA(NionS)=(/1.,4.,14.,16.,28.,30.,32./)
 REAL(4),   PARAMETER :: nAM(NionS)=(/1.,4.,14.,16.,28.,30.,32./)
 REAL(4),   PARAMETER :: MiS(NionS)=(/1.,4.,14.,16.,28.,30.,32./)*Mp
 REAL(4),   PARAMETER :: MnS(NionS)=(/1.,4.,14.,16.,28.,30.,32./)*Mp
!***********************************************************************
!  THE SPATIAL POSTION OF CALCULATING THE EIGNEVALUES OF THE EIGENMODES
!***********************************************************************
 LOGICAL                 :: XLOCAL,XQLOCAL,XNLOCAL
 LOGICAL                 :: YLOCAL,YQLOCAL,YNLOCAL
 LOGICAL                 :: ZLOCAL,ZQLOCAL,ZNLOCAL
!*********** NEUTRALS, IONS, AND ELECTRONS DENSITIES ***********
!! NnS   :: THE DENSITY OF EACH NEUTRAL SPECIES (1/M^3)
!! Nn    :: TOTAL DENSITY OF ALL NEUTRAL SPECIES (1/M^3)
!! NiS   :: THE DENSITY OF EACH ION SPECIES  (1/M^3)
!! Ni    :: TOTAL DENSITY OF ALL ION SPECIES (1/M^3)
!! Ne    :: ELECTRON DENSITY (1/M^3)
 REAL(4), ALLOCATABLE :: NnS(:,:,:,:)
 REAL(4), ALLOCATABLE :: Nn(:,:,:)
 REAL(4), ALLOCATABLE :: NiS(:,:,:,:)
 REAL(4), ALLOCATABLE :: Ni(:,:,:)
 REAL(4), ALLOCATABLE :: Ne(:,:,:)
 REAL(4), ALLOCATABLE :: Lne(:,:,:)
!*********** NEUTRALS, IONS, AND ELECTRONS TEMPERATURES ***********
!! TnS   :: TEMPERATURE OF EACH NEUTRAL SPECIES (KELVIN)
!! Tn    :: TEMPERATURE OF ALL NEUTRAL SPECIES (KELVIN)
!! TiS   :: TEMPERATURE OF EACH ION SPECIES (KELVIN)
!! Ti    :: TEMPERATURE OF ALL ION SPECIES (KELVIN)
!! Te    :: TEMPERATURE OF ELECTRONS (KELVIN)
 REAL(4), ALLOCATABLE :: TnS(:,:,:,:)
 REAL(4), ALLOCATABLE :: Tn(:,:,:)
 REAL(4), ALLOCATABLE :: TiS(:,:,:,:)
 REAL(4), ALLOCATABLE :: Ti(:,:,:)
 REAL(4), ALLOCATABLE :: Te(:,:,:)
!***************** MAGNETIC FIELD COMPONENTS ***********************
!! Babs   :: MAGNETIC FIELD STENGTH (H)
!! Br     :: VERTICAL MAGNETIC FIELD STRENGTH (Hz) (POSITIVE UPWARD)
!! Btheta :: NORTH-SOUTH MAGNETIC FIELD STRENGTH (Hx) (POSITIVE NORTHWARD))
!! Bphi   :: EAST-WEST MAGNETIC FIELD STRENGTH (Hy) (POSITIVE EASTWARD)
 REAL(4), ALLOCATABLE :: Babs(:,:,:)
 REAL(4), ALLOCATABLE :: Br(:,:,:)
 REAL(4), ALLOCATABLE :: Btheta(:,:,:)
 REAL(4), ALLOCATABLE :: Bphi(:,:,:)
!******************** NEUTRAL WINDS SPEEDS  ************************
!! Vzonal :: THE ZONAL WIND SPEED (m/s) - POSITIVE EASTWARD
!! Vmerid :: THE MERIDIONAL WIND SPEED (m/s) - POSITVE NORTHWARD
 REAL(4), ALLOCATABLE :: Vzonal(:,:,:)
 REAL(4), ALLOCATABLE :: Vmerid(:,:,:)
!**************** ELECTRIC FIELD AND POTENTIAL ********************
!! EFIELD :: THE ELECTRIC FIELD (V/m)
!! EPOTEN :: THE ELECTRIC POTENTIAL (V)
 REAL(4), ALLOCATABLE :: EFIELD(:,:,:)
 REAL(4), ALLOCATABLE :: EPOTEN(:,:,:)
!***** ION-NEUTRAL AND ELECTRON-NEUTRAL COLLISION FREQUENCIES ******
!! NUinS :: ION-NEUTRAL RESONANT COLLISION FREQUENCY OF EACH SPECIES (1/S)
!! NUin  :: TOTAL ION-NEUTRAL RESONANT COLLISION FREQUENCY OF ALL SPECIES (1/S)
!! NUenS :: ELECTRON-NEUTRAL COLLISION FREQUECNY OF EACH SPECIES (1/S)
!! NUen  :: TOTAL ELECTRON-NEUTRAL COLLISION FREQUENCY OF ALL SPECIES (1/S)
!! NUeiS :: ELECTRON-ION COLLISION FREQUENCY OF EACH SPECIES (1/S)
!! NUei  :: TOTAL ELECTRON-ION SPECIES COLLISION FREQUENCY OF ALL SPECIES (1/S)
 REAL(4), ALLOCATABLE :: NUinS(:,:,:,:)
 REAL(4), ALLOCATABLE :: NUin(:,:,:)
 REAL(4), ALLOCATABLE :: NUenS(:,:,:,:)
 REAL(4), ALLOCATABLE :: NUen(:,:,:)
 REAL(4), ALLOCATABLE :: NUeiS(:,:,:,:)
 REAL(4), ALLOCATABLE :: NUei(:,:,:)
!************* IONS AND ELECTRONS PLASMA FREQUENCIES ****************
 REAL(4), ALLOCATABLE :: OMEGApiS(:,:,:,:)
 REAL(4), ALLOCATABLE :: OMEGApi(:,:,:)
 REAL(4), ALLOCATABLE :: OMEGApe(:,:,:)
!*********** IONS AND ELECTRONS CYCLOTRON FREQUENCIES ****************
 REAL(4), ALLOCATABLE :: OMEGAciS(:,:,:,:)
 REAL(4), ALLOCATABLE :: OMEGAci(:,:,:)
 REAL(4), ALLOCATABLE :: OMEGAce(:,:,:)
!**************** IONS AND ELECTRONS GYRO-RADIUS *********************
 REAL(4), ALLOCATABLE :: RHOiS(:,:,:,:)
 REAL(4), ALLOCATABLE :: RHOi(:,:,:)
 REAL(4), ALLOCATABLE :: RHOe(:,:,:)
!************* IONS AND ELECTRONS THERMAL VELOCITIES *****************
 REAL(4), ALLOCATABLE :: VthiS(:,:,:,:)
 REAL(4), ALLOCATABLE :: Vthe(:,:,:)
 REAL(4), ALLOCATABLE :: Vthi(:,:,:)
 REAL(4), ALLOCATABLE :: CsS(:,:,:,:)
 REAL(4), ALLOCATABLE :: Cs(:,:,:)
!********************* ALFVEN VELCOCITY **********************
!! VAlfvenS :: ALFVEN SPEED FOR EACH ION SPECIES
!! VAlfven  :: ALFVEN SPEED FOR IONS
 REAL(4), ALLOCATABLE :: VAlfvenS(:,:,:,:)
 REAL(4), ALLOCATABLE :: VAlfven(:,:,:)
!************* HALL AND PEDERSEN MOBILITIES ******************
!! MUeH  :: HALL MOBILITY OF ELECTRONS
!! MUeP  :: PEDERSEN MOBILITY OF ELECTRONS
!! MUiHS :: HALL MOBILITY OF EACH ION SPECIES
!! MUiPS :: PEDERSEN MOBILITY OF EACH ION SPECIES
!! MUiH  :: HALL MOBILITY OF ALL ION SPECIES
!! MUiP  :: PEDERSEN MOBILITY OF ALL ION SPECIES
 REAL(4), ALLOCATABLE :: MUeH(:,:,:)
 REAL(4), ALLOCATABLE :: MUeP(:,:,:)
 REAL(4), ALLOCATABLE :: MUiHS(:,:,:,:)
 REAL(4), ALLOCATABLE :: MUiPS(:,:,:,:)
 REAL(4), ALLOCATABLE :: MUiH(:,:,:)
 REAL(4), ALLOCATABLE :: MUiP(:,:,:)
!************* HALL AND PEDERSEN DIFFUSIONS ******************
!! DeH   :: HALL DIFFUSION OF ELECTRONS
!! DeP   :: PEDERSEN DIFFUSION OF ELECTRONS
!! DiHS  :: HALL DIFFUSION OF EACH ION SPECIES
!! DiPS  :: PEDERSEN DIFFUSION OF EACH ION SPECIES
!! DiH   :: HALL DIFFUSION OF ALL ION SPECIES
!! DiP   :: PEDERSEN DIFFUSION OF ALL ION SPECIES
 REAL(4), ALLOCATABLE :: DeH(:,:,:)
 REAL(4), ALLOCATABLE :: DeP(:,:,:)
 REAL(4), ALLOCATABLE :: DiHS(:,:,:,:)
 REAL(4), ALLOCATABLE :: DiPS(:,:,:,:)
 REAL(4), ALLOCATABLE :: DiH(:,:,:)
 REAL(4), ALLOCATABLE :: DiP(:,:,:)
!********** HALL, PEDERSEN, AND PARALLEL CONDUCTIVITIES ***********
!! sigmaHS  :: HALL CONDUCTIVITY FOR EACH ION SPECIES
!! sigmaPS  :: PEDERSEN CONDUCTIVITY FOR EACH ION SPECIES
!! sigmaOS  :: PARALLEL CONDUCTIVITY FOR EACH ION SPECIES
!! sigmaH   :: HALL CONDUCTIVITY
!! sigmaP   :: PEDERSEN CONDUCTIVITY
!! sigmaO   :: PARALLEL CONDUCTIVITY
!! LAMBDAD :: DEBY SHIELDING LENGTH
!! Vion     ::  IONS DRIFTS
!! Vexb     :: ExB DRIFTS
 REAL(4), ALLOCATABLE :: sigmaHS(:,:,:,:)
 REAL(4), ALLOCATABLE :: sigmaPS(:,:,:,:)
 REAL(4), ALLOCATABLE :: sigmaOS(:,:,:,:)
 REAL(4), ALLOCATABLE :: sigmaH(:,:,:)
 REAL(4), ALLOCATABLE :: sigmaP(:,:,:)
 REAL(4), ALLOCATABLE :: sigmaO(:,:,:)
 REAL(4), ALLOCATABLE :: LAMBDAD(:,:,:)
 REAL(4), ALLOCATABLE :: VionS(:,:,:,:)
 REAL(4), ALLOCATABLE :: Vion(:,:,:)
 REAL(4), ALLOCATABLE :: Vexb(:,:,:)


 CONTAINS


!**************************************************************
!************** CALCULATING IONOSPHERE BACKGROUND *************
!**************************************************************
 SUBROUTINE SYSBG(LOCALTYPE,LAT1D,LON1D,ALT1D,LDYYYY,LDMM,LDDD,LTHUR,LTMIN,LTSEC)
  USE RDSVNETCDF
  IMPLICIT NONE
!******** INPUT VARIABLES ************
  REAL(4),     INTENT(IN)          :: LAT1D(:),LON1D(:),ALT1D(:)
  CHARACTER(*),INTENT(IN)          :: LOCALTYPE(:)
  INTEGER(4),  INTENT(IN),OPTIONAL :: LDYYYY,LDMM,LDDD,LTHUR,LTMIN,LTSEC

!******** DECLARED VARIABLES *********
  LOGICAL         :: JF(50)=.FALSE.
  LOGICAL         :: fexist=.FALSE.
  CHARACTER(15)   :: DIMSNAME(4)=(/CHARACTER(15) :: "LAT","LON","ALT","Seconds Of Day"/)
  CHARACTER(6)    :: DIMSUNIT(4)=(/CHARACTER(6)  :: "Degree","Degree","km","second"/)
  CHARACTER(25)   :: LFLDNAME,LFLDUNIT
  CHARACTER(10)   :: IONOLOCALTYPE(3)
  CHARACTER(30)   :: IONODATAPATH
  CHARACTER(8)    :: srtDATE
  INTEGER(4)      :: MATDIMS3D(3)
  INTEGER(4)      :: nLAT,nLON,nALT
  INTEGER(4)      :: YYYY,DDD,YYDDD,MM,DD,MMDD,NRDAYMO
  INTEGER(4)      :: mas
  INTEGER(4)      :: iLAT,iLON,iALT
  INTEGER(4)      :: I,J,K,L,ICOUNTER=0
  INTEGER(4)      :: LOCALTIME
  INTEGER(4)      :: NeMAXLOC(3),NeMINLOC(3)
  INTEGER(4),SAVE :: ACCESSID=1
  REAL(4)         :: LOCTIME,LOCHR,UTSEC
  REAL(4)         :: WS(2),ND(9),NT(2),CD(7),CT(2),OTHR(3)
  REAL(4)         :: fb,f10p7
  REAL(4)         :: ap(7),SW(25)
  REAL(4)         :: R,ALT
  REAL(4)         :: PHIG,radPHIG,THETAG,radTHETAG
  REAL(4)         :: PHIGD,radPHIGD,THETAGD,radTHETAGD


  IF(SIZE(LOCALTYPE).EQ.1) THEN
   IONOLOCALTYPE(1)=TRIM(LOCALTYPE(1))
   IONOLOCALTYPE(2)=TRIM(LOCALTYPE(1))
   IONOLOCALTYPE(3)=TRIM(LOCALTYPE(1))
  ELSE IF(SIZE(LOCALTYPE).EQ.2) THEN
   IONOLOCALTYPE(1)=TRIM(LOCALTYPE(1))
   IONOLOCALTYPE(2)=TRIM(LOCALTYPE(2))
   IONOLOCALTYPE(3)=TRIM(LOCALTYPE(2))
  ELSE IF(SIZE(LOCALTYPE).EQ.3) THEN
   IONOLOCALTYPE(1)=TRIM(LOCALTYPE(1))
   IONOLOCALTYPE(2)=TRIM(LOCALTYPE(2))
   IONOLOCALTYPE(3)=TRIM(LOCALTYPE(3))
  ELSE IF(SIZE(LOCALTYPE).GT.3) THEN
   PRINT*, "WARNING: LOCALTYPE DIMENSIONS IS GREATER THAN THE SYSTEM DIMESNIONS"
   IONOLOCALTYPE(1)=TRIM(LOCALTYPE(1))
   IONOLOCALTYPE(2)=TRIM(LOCALTYPE(2))
   IONOLOCALTYPE(3)=TRIM(LOCALTYPE(3))
  END IF

 !MATDIMS3D=SHAPE(LAT3D)
  MATDIMS3D(1)=SIZE(LAT1D)
  MATDIMS3D(2)=SIZE(LON1D)
  MATDIMS3D(3)=SIZE(ALT1D)

  
  IF(to_LowerCase(IONOLOCALTYPE(1)).EQ."") THEN
   nLAT=1
  ELSE IF(to_LowerCase(IONOLOCALTYPE(1)).EQ."local") THEN
   nLAT=1
  ELSE IF(to_LowerCase(IONOLOCALTYPE(1)).EQ."nonlocal") THEN
   nLAT=MATDIMS3D(1)
  ELSE IF(to_LowerCase(IONOLOCALTYPE(1)).EQ."quasilocal") THEN
   nLAT=MATDIMS3D(1)
  END IF

  IF(to_LowerCase(IONOLOCALTYPE(2)).EQ."") THEN
   nLON=1
  ELSE IF(to_LowerCase(IONOLOCALTYPE(2)).EQ."local") THEN
   nLON=1
  ELSE IF(to_LowerCase(IONOLOCALTYPE(2)).EQ."nonlocal") THEN
   nLON=MATDIMS3D(2)
  ELSE IF(to_LowerCase(IONOLOCALTYPE(2)).EQ."quasilocal") THEN
   nLON=MATDIMS3D(2)
  END IF

  IF(to_LowerCase(IONOLOCALTYPE(3)).EQ."") THEN
   nALT=1
  ELSE IF(to_LowerCase(IONOLOCALTYPE(3)).EQ."local") THEN
   nALT=1
  ELSE IF(to_LowerCase(IONOLOCALTYPE(3)).EQ."nonlocal") THEN
   nALT=MATDIMS3D(3)
  ELSE IF(to_LowerCase(IONOLOCALTYPE(3)).EQ."quasilocal") THEN
   nALT=MATDIMS3D(3)
  END IF

  IF(nLAT.EQ.1) THEN
   XLOCAL=.TRUE.
   XQLOCAL=.FALSE.
   XNLOCAL=.FALSE.
  ELSE IF(nLAT.EQ.XDIM) THEN
   XLOCAL =.FALSE.
   XQLOCAL=.FALSE.
   XNLOCAL=.TRUE.
  ELSE IF(nLAT.LT.XDIM.AND.nLAT.GT.1) THEN
   XLOCAL =.FALSE.
   XQLOCAL=.TRUE.
   XNLOCAL=.FALSE.
  END IF

  IF(nLON.EQ.1) THEN
   YLOCAL=.TRUE.
   YQLOCAL=.FALSE.
   YNLOCAL=.FALSE.
  ELSE IF(nLON.EQ.YDIM) THEN
   YLOCAL =.FALSE.
   YQLOCAL=.FALSE.
   YNLOCAL=.TRUE.
  ELSE IF(nLON.LT.YDIM.AND.nLON.GT.1) THEN
   YLOCAL =.FALSE.
   YQLOCAL=.TRUE.
   YNLOCAL=.FALSE.
  END IF

  IF(nALT.EQ.1) THEN
   ZLOCAL=.TRUE.
   ZQLOCAL=.FALSE.
   ZNLOCAL=.FALSE.
  ELSE IF(nALT.EQ.ZDIM) THEN
   ZLOCAL =.FALSE.
   ZQLOCAL=.FALSE.
   ZNLOCAL=.TRUE.
  ELSE IF(nALT.LT.ZDIM.AND.nALT.GT.1) THEN
   ZLOCAL =.FALSE.
   ZQLOCAL=.TRUE.
   ZNLOCAL=.FALSE.
  END IF

  IF(PRESENT(LDYYYY)) THEN
   MMDD=100*LDMM+LDDD
   YYYY=LDYYYY;MM=LDMM;DD=LDDD
   LOCTIME=LTHUR/1.0+LTMIN/60.0+LTSEC/3600.0
  ELSE
   YYYY=DTYYYYMAT(1);MM=DTMMMAT(1);DD=DTDDMAT(1);MMDD=DTMMDDMAT(1)
   LOCTIME=LTHURMAT(1)/1.0+LTMINMAT(1)/60.0+LTSECMAT(1)/3600.0
  END IF

  mas=48

  CALL IDDD(0,YYYY,MM,DD,DDD,NRDAYMO)

  PRINT*, "IONOSPHERE BACKGROUND FIELDS INITIALIZATION >>> STARTED!"

!! ALLOCATING REQUIRED IONOSPHERE BACKGROUND PHYSICAL QUANTITIES
  ALLOCATE(Ne(nLAT,nLON,nALT))
  ALLOCATE(Ni(nLAT,nLON,nALT))
  ALLOCATE(Nn(nLAT,nLON,nALT))
  ALLOCATE(Te(nLAT,nLON,nALT))
  ALLOCATE(Ti(nLAT,nLON,nALT))
  ALLOCATE(Tn(nLAT,nLON,nALT))
  ALLOCATE(NiS(nLAT,nLON,nALT,NionS))
  ALLOCATE(NnS(nLAT,nLON,nALT,NionS))
  ALLOCATE(TiS(nLAT,nLON,nALT,NionS))
  ALLOCATE(TnS(nLAT,nLON,nALT,NionS))

  ALLOCATE(Babs(nLAT,nLON,nALT))
  ALLOCATE(Br(nLAT,nLON,nALT))
  ALLOCATE(Bphi(nLAT,nLON,nALT))
  ALLOCATE(Btheta(nLAT,nLON,nALT))

  ALLOCATE(Vzonal(nLAT,nLON,nALT))
  ALLOCATE(Vmerid(nLAT,nLON,nALT))

  IF(IonoLne) ALLOCATE(Lne(nLAT,nLON,nALT))

  IF(IonoOMEGApe) THEN
   ALLOCATE(OMEGApe(nLAT,nLON,nALT))
  END IF
  IF(IonoOMEGApi) THEN
   ALLOCATE(OMEGApiS(nLAT,nLON,nALT,NionS))
   ALLOCATE(OMEGApi(nLAT,nLON,nALT))
  END IF

  IF(IonoVthe.OR.IonoRHOe) THEN
   ALLOCATE(Vthe(nLAT,nLON,nALT))
  END IF
  IF(IonoVthi.OR.IonoRHOi) THEN
   ALLOCATE(VthiS(nLAT,nLON,nALT,NionS))
   ALLOCATE(Vthi(nLAT,nLON,nALT))
  END IF

  IF(IonoOMEGAce.OR.IonoRHOe.OR.IonoMUeH.OR.IonoMUeP.OR.IonoDeH.OR.IonoDeP.OR.IonoSigmaH.OR.IonoSigmaP) THEN
   ALLOCATE(OMEGAce(nLAT,nLON,nALT))
  END IF
  IF(IonoOMEGAci.OR.IonoRHOi.OR.IonoMUiH.OR.IonoMUiP.OR.IonoDiH.OR.IonoDiP.OR.IonoSigmaH.OR.IonoSigmaP) THEN
   ALLOCATE(OMEGAciS(nLAT,nLON,nALT,NionS))
   ALLOCATE(OMEGAci(nLAT,nLON,nALT))
  END IF

  IF(IonoNUen.OR.IonoMUeH.OR.IonoMUeP.OR.IonoDeH.OR.IonoDeP.OR.IonoSigmaH.OR.IonoSigmaP.OR.IonoSigmaO) THEN
   ALLOCATE(NUenS(nLAT,nLON,nALT,NionS))
   ALLOCATE(NUen(nLAT,nLON,nALT))
  END IF
  IF(IonoNUin.OR.IonoMUiH.OR.IonoMUiP.OR.IonoDiH.OR.IonoDiP.OR.IonoSigmaH.OR.IonoSigmaP.OR.IonoSigmaO) THEN
   ALLOCATE(NUinS(nLAT,nLON,nALT,NionS))
   ALLOCATE(NUin(nLAT,nLON,nALT))
  END IF

  IF(IonoRHOe)    ALLOCATE(RHOe(nLAT,nLON,nALT))
  IF(IonoRHOi)    THEN
   ALLOCATE(RHOiS(nLAT,nLON,nALT,NionS))
   ALLOCATE(RHOi(nLAT,nLON,nALT))
  END IF

  IF(IonoMUeH)    ALLOCATE(MUeH(nLAT,nLON,nALT))
  IF(IonoMUiH)    THEN
   ALLOCATE(MUiHS(nLAT,nLON,nALT,NionS))
   ALLOCATE(MUiH(nLAT,nLON,nALT))
  END IF
  IF(IonoMUeP)    ALLOCATE(MUeP(nLAT,nLON,nALT))
  IF(IonoMUiP)    THEN
   ALLOCATE(MUiPS(nLAT,nLON,nALT,NionS))
   ALLOCATE(MUiP(nLAT,nLON,nALT))
  END IF
  IF(IonoDeH)     ALLOCATE(DeH(nLAT,nLON,nALT))
  IF(IonoDiH)     THEN
   ALLOCATE(DiHS(nLAT,nLON,nALT,NionS))
   ALLOCATE(DiH(nLAT,nLON,nALT))
  END IF
  IF(IonoDeP)     ALLOCATE(DeP(nLAT,nLON,nALT))
  IF(IonoDiP)     THEN
   ALLOCATE(DiPS(nLAT,nLON,nALT,NionS))
   ALLOCATE(DiP(nLAT,nLON,nALT))
  END IF

  IF(IonoLAMBDAD) ALLOCATE(LAMBDAD(nLAT,nLON,nALT))
  IF(IonoEPOTEN)  ALLOCATE(EPOTEN(nLAT,nLON,nALT))
  IF(IonoEFIELD)  ALLOCATE(EFIELD(nLAT,nLON,nALT))

  IF(IonoVexb)  ALLOCATE(Vexb(nLAT,nLON,nALT))

  IF(IonoVion) THEN
   ALLOCATE(VionS(nLAT,nLON,nALT,NionS))
   ALLOCATE(Vion(nLAT,nLON,nALT))
  END IF
  IF(IonoCs)      THEN
   ALLOCATE(CsS(nLAT,nLON,nALT,NionS))
   ALLOCATE(Cs(nLAT,nLON,nALT))
  END IF
  IF(IonoVAlfven) THEN
   ALLOCATE(VAlfvenS(nLAT,nLON,nALT,NionS))
  END IF

  IF(IonoSigmaO)  THEN
   ALLOCATE(sigmaOS(nLAT,nLON,nALT,NionS))
   ALLOCATE(sigmaO(nLAT,nLON,nALT))
  END IF
  IF(IonoSigmaH)  THEN
   ALLOCATE(sigmaHS(nLAT,nLON,nALT,NionS))
   ALLOCATE(sigmaH(nLAT,nLON,nALT))
  END IF
  IF(IonoSigmaP)  THEN
   ALLOCATE(sigmaPS(nLAT,nLON,nALT,NionS))
   ALLOCATE(sigmaP(nLAT,nLON,nALT))
  END IF

  IF(EMPIRICAL) THEN
   PRINT*, "EMPIRICAL: FILLING UP THE BASIC QUANTITIES >>> STARTED"
 !$OMP PARALLEL DEFAULT(SHARED) PRIVATE(I,J,K,ALT,PHIG,THETAG,LOCALTIME,LOCHR)
 !$OMP DO
   DO I=1,nLAT
    DO J=1,nLON
     DO K=1,nALT
      IF(ZLOCAL) THEN
       ALT=REAL(ALT1D(ZDIM/2+1))
      ELSE IF(ZNLOCAL) THEN
       ALT=REAL(ALT1D(K))
      END IF
      LOCALTIME=FLOAT(LTHURMAT(1))+((FLOAT(LTMINMAT(1))*60.0)/3600.0)+FLOAT(LTSECMAT(1))/3600.0
      IF(YLOCAL) THEN
       LOCHR=LOCALTIME+REAL(LON1D(YDIM/2+1)/15.0)
       PHIG=REAL(LON1D(YDIM/2+1))
      ELSE IF(YNLOCAL) THEN
       LOCHR=LOCALTIME+REAL(LON1D(J)/15.0)
       PHIG=REAL(LON1D(J))
      END IF
      IF(XLOCAL) THEN
       THETAG=REAL(LAT1D(XDIM/2+1))
      ELSE IF(XNLOCAL) THEN
       THETAG=REAL(LAT1D(I))
      END IF
     !ALT=REAL(ALT1D(K))
     !LOCALTIME=FLOAT(LTHURMAT(1))+((FLOAT(LTMINMAT(1))*60.0)/3600.0)+FLOAT(LTSECMAT(1))/3600.0
     !LOCHR=LOCALTIME+REAL(LON1D(J)/15.0)
     !PHIG=REAL(LON1D(J))
      CALL IYYDDD(YYYY,DDD,LOCHR,PHIG,YYDDD,UTSEC)
     !THETAG=REAL(LAT1D(I))
      CALL IONOCARRIERS(ALT,THETAG,PHIG,YYDDD,UTSEC,CD,CT,OTHR)
!!!   CALL TSELEC(SW)
      NiS(I,J,K,iH1p) =CD(3)
      IF(NiS(I,J,K,iH1p).LT.1) NiS(I,J,K,iH1P)=0.0
      NiS(I,J,K,iHe1p)=CD(4)
      IF(NiS(I,J,K,iHe1p).LT.1) NiS(I,J,K,iHe1P)=0.0
      NiS(I,J,K,iN1p) =CD(7)
      IF(NiS(I,J,K,iN1p).LT.1) NiS(I,J,K,iN1P)=0.0
      NiS(I,J,K,iO1p) =CD(2)
      IF(NiS(I,J,K,iO1p).LT.1) NiS(I,J,K,iO1P)=0.0
      NiS(I,J,K,iNO1p)=CD(6)
      IF(NiS(I,J,K,iNO1p).LT.1) NiS(I,J,K,iNO1P)=0.0
      NiS(I,J,K,iN21p)=0.0
      NiS(I,J,K,iO21p)=CD(5)
      IF(NiS(I,J,K,iO21p).LT.1) NiS(I,J,K,iO21P)=0.0
      Ni(I,J,K)=SUM(NiS(I,J,K,:))
      Ne(I,J,K)=CD(1)

      TiS(I,J,K,iH1p) =CT(2)
      TiS(I,J,K,iHe1p)=CT(2)
      TiS(I,J,K,iN1p) =CT(2)
      TiS(I,J,K,iO1p) =CT(2)
      TiS(I,J,K,iNO1p)=CT(2)
      TiS(I,J,K,iN21p)=CT(2)
      TiS(I,J,K,iO21p)=CT(2)
      Ti(I,J,K)=SUM(TiS(I,J,K,:))/NionS
      Te(I,J,K)=CT(1)

      ap(:)=OTHR(3)
      f10p7=OTHR(1)
      fb=OTHR(2)

      CALL GTD7(YYDDD,UTSEC,ALT,THETAG,PHIG,LOCHR,FB,F10p7,AP,mas,ND,NT)
!     CALL METERS(.TRUE.)
!     CALL TRETRV(SW)
      NnS(I,J,K,aH) =ND(7)*1e6
      IF(NnS(I,J,K,aH).LT.1) NnS(I,J,K,aH)=0.0
      NnS(I,J,K,aHe)=ND(1)*1e6
      IF(NnS(I,J,K,aHe).LT.1) NnS(I,J,K,aHe)=0.0
      NnS(I,J,K,aN) =ND(8)*1e6
      IF(NnS(I,J,K,aN).LT.1) NnS(I,J,K,aN)=0.0
      NnS(I,J,K,aO) =ND(2)*1e6
      IF(NnS(I,J,K,aO).LT.1) NnS(I,J,K,aO)=0.0
      NnS(I,J,K,aN2)=ND(3)*1e6
      IF(NnS(I,J,K,aN2).LT.1) NnS(I,J,K,aN2)=0.0
      NnS(I,J,K,aO2)=ND(4)*1e6
      IF(NnS(I,J,K,aO2).LT.1) NnS(I,J,K,aO2)=0.0
      NnS(I,J,K,aNO)=(0.4*EXP(-3700.0/TnS(I,J,K,aNO))*NnS(I,J,K,aO2)+(5.0E-7)*NnS(I,J,K,aO))*1e6
      Nn(I,J,K)=SUM(NnS(I,J,K,:))

      TnS(I,J,K,aH) =NT(2)
      TnS(I,J,K,aHe)=NT(2)
      TnS(I,J,K,aN) =NT(2)
      TnS(I,J,K,aO) =NT(2)
      TnS(I,J,K,aNO)=NT(2)
      TnS(I,J,K,aN2)=NT(2)
      TnS(I,J,K,aO2)=NT(2)
      Tn(I,J,K)=SUM(TnS(I,J,K,:))/NneutralS

      CALL GWS5(YYDDD,UTSEC,ALT,THETAG,PHIG,LOCHR,FB,F10p7,AP,WS)
      Vmerid(I,J,K)=WS(1)
      Vzonal(I,J,K)=WS(2)
     END DO
    END DO
   END DO
 !$OMP END DO
 !$OMP END PARALLEL
   PRINT*, "EMPIRICAL: FILLING UP THE BASIC QUANTITIES >>> FINISHED"
  ELSE IF(TIEGCM) THEN
   WRITE(srtDATE,"(I8)") srtDT
   IONODATAPATH="../ionoNETCDF/tiegcm"// TRIM(srtDATE) //".nc"
   INQUIRE(FILE=TRIM(IONODATAPATH),EXIST=fexist)
   IF(fexist) THEN
    CALL TIEGCMDATA(TRIM(IONODATAPATH),"POTEN",srtDT,srtLT,EPOTEN)
    CALL TIEGCMDATA(TRIM(IONODATAPATH),"NE",srtDT,srtLT,Ne)
    Ne=1000.0*Ne
    CALL TIEGCMDATA(TRIM(IONODATAPATH),"TE",srtDT,srtLT,Te)
    CALL TIEGCMDATA(TRIM(IONODATAPATH),"DEN",srtDT,srtLT,Tn)
    CALL TIEGCMDATA(TRIM(IONODATAPATH),"UI_ExB",srtDT,srtLT,Vzonal)
    Vzonal=0.01*Vzonal
    CALL TIEGCMDATA(TRIM(IONODATAPATH),"VI_ExB",srtDT,srtLT,Vmerid)
    Vmerid=0.01*Vmerid
   !CALL TIEGCMDATA(TRIM(IONODATAPATH),"WI_ExB",srtDT,srtLT,Vzonal)
    CALL TIEGCMDATA(TRIM(IONODATAPATH),"TI",srtDT,srtLT,Ti)
    CALL TIEGCMDATA(TRIM(IONODATAPATH),"TN",srtDT,srtLT,Ti)
    DO L=1,7
     TiS(:,:,:,L)=Ti
     TnS(:,:,:,L)=Tn
    END DO
   ELSE
    PRINT*, "TIEGCM netCDF DATA FOR THE DATE IS NOT FOUND"
    STOP
   END IF
  END IF

  PRINT*, "CALCULATING SELECTED QUANTITIES >>> STARTED"
 !$OMP PARALLEL DEFAULT(SHARED) PRIVATE(I,J,K,R,radPHIG,radTHETAG)
 !$OMP DO
  DO I=1,nLAT
   DO J=1,nLON
    DO K=1,nALT
     R=RE+ALT
     radPHIG=DEG2RAD(LON1D(J)+180.)
     radTHETAG=DEG2RAD(LAT1D(I)+90.)
     CALL EDBFIELD(R,radTHETAG,radPHIG,REAL(YYYY),Babs(I,J,K),Btheta(I,J,K),Bphi(I,J,K),Br(I,J,K))

     IF(ALLOCATED(NUen)) THEN
      NUenS(I,J,K,aH) =4.5E-16*NnS(I,J,K,aH)*SQRT(Te(I,J,K))
      NUenS(I,J,K,aHe)=4.6E-16*NnS(I,J,K,aHe)*SQRT(Te(I,J,K))
      NUenS(I,J,K,aN) =2.6E-16*NnS(I,J,K,aN)*SQRT(Te(I,J,K))
      NUenS(I,J,K,aO) =2.8E-16*NnS(I,J,K,aO)*SQRT(Te(I,J,K))
      NUenS(I,J,K,aN2)=2.5E-17*NnS(I,J,K,aN2)*Te(I,J,K)
      NUenS(I,J,K,aNO)=1.4E-16*NnS(I,J,K,aNO)*SQRT(Te(I,J,K))
      NUenS(I,J,K,aO2)=1.5E-16*NnS(I,J,K,aO2)*SQRT(Te(I,J,K))

      NUen(I,J,K)=SUM(NUenS(I,J,K,:))
     END IF
     IF(ALLOCATED(NUin)) THEN
      NUinS(I,J,K,iH1p) =(2.6E-15*(NnS(I,J,K,aH)+NiS(I,J,K,iH1p)))/SQRT(iA(iH1p))
      NUinS(I,J,K,iHe1p)=(2.6E-15*(NnS(I,J,K,aHe)+NiS(I,J,K,iHe1p)))/SQRT(iA(iHe1p))
      NUinS(I,J,K,iN1p) =(2.6E-15*(NnS(I,J,K,aN)+NiS(I,J,K,iN1p)))/SQRT(iA(iN1p))
      NUinS(I,J,K,iO1p) =(2.6E-15*(NnS(I,J,K,aO)+NiS(I,J,K,iO1p)))/SQRT(iA(iO1p))
      NUinS(I,J,K,iN21p)=(2.6E-15*(NnS(I,J,K,aN2)+NiS(I,J,K,iN21p)))/SQRT(iA(iN21p))
      NUinS(I,J,K,iNO1p)=(2.6E-15*(NnS(I,J,K,aNO)+NiS(I,J,K,iNO1p)))/SQRT(iA(iNO1p))
      NUinS(I,J,K,iO21p)=(2.6E-15*(NnS(I,J,K,aO2)+NiS(I,J,K,iO21p)))/SQRT(iA(iO21p))

      NUin(I,J,K)=SUM(NUinS(I,J,K,:))
     END IF

     IF(ALLOCATED(OMEGApe)) OMEGApe(I,J,K)=SQRT(Ne(I,J,K)*(Qe/EPSILON0)*(Qe/Me))
     IF(ALLOCATED(Vthe))    Vthe(I,J,K)=SQRT(Cpve*KB*Te(I,J,K)/Me)
     IF(ALLOCATED(OMEGAce)) OMEGAce(I,J,K)=(Qe*Babs(I,J,K))/Me
     IF(ALLOCATED(RHOe))    RHOe(I,J,K)=Vthe(I,J,K)/OMEGAce(I,J,K)

     IF(ALLOCATED(MUeH)) MUeH(I,J,K)=-(Qe/Me)*(OMEGAce(I,J,K)/(OMEGAce(I,J,K)**2+NUen(I,J,K)**2))
     IF(ALLOCATED(MUeP)) MUeP(I,J,K)=-(Qe/Me)*(NUen(I,J,K)/(OMEGAce(I,J,K)**2+NUen(I,J,K)**2))
     IF(ALLOCATED(DeH))  DeH(I,J,K) =-(KB*Te(I,J,K)/Me)*(OMEGAce(I,J,K)/(OMEGAce(I,J,K)**2+NUen(I,J,K)**2))
     IF(ALLOCATED(DeP))  DeP(I,J,K) =(KB*Te(I,J,K)/Me)*(NUen(I,J,K)/(OMEGAce(I,J,K)**2+NUen(I,J,K)**2))

     DO L=1,NionS
      IF(ALLOCATED(OMEGApi)) OMEGApiS(I,J,K,L)=SQRT(NiS(I,J,K,L)*(Qp/EPSILON0)*(Qp/MiS(L)))
      IF(ALLOCATED(Vthi))    VthiS(I,J,K,L)=SQRT(Cpvi*KB*TiS(I,J,K,L)/MiS(L))
      IF(ALLOCATED(Cs))      CsS(I,J,K,L)=SQRT(KB*(Cpve*Te(I,J,K)+Cpvi*TiS(I,J,K,L))/MiS(L))
      IF(ALLOCATED(OMEGAci)) OMEGAciS(I,J,K,L)=(Qp*Babs(I,J,K))/MiS(L)
      IF(ALLOCATED(RHOi))    RHOiS(I,J,K,L)=VthiS(I,J,K,L)/OMEGAciS(I,J,K,L)
      IF(ALLOCATED(VAlfven)) VAlfvenS(I,J,K,L)=Babs(I,J,K)/SQRT(MU0*NiS(I,J,K,L)*MiS(L))

      IF(ALLOCATED(MUiH)) MUiHS(I,J,K,L)=(Qp/MiS(L))*(OMEGAciS(I,J,K,L)/(OMEGAciS(I,J,K,L)**2+NUinS(I,J,K,L)**2))
      IF(ALLOCATED(MUiP)) MUiPS(I,J,K,L)=(Qp/MiS(L))*(NUinS(I,J,K,L)/(OMEGAciS(I,J,K,L)**2+NUinS(I,J,K,L)**2))
      IF(ALLOCATED(DiH))  DiHS(I,J,K,L) =(KB*TiS(I,J,K,L)/MiS(L))*(OMEGAciS(I,J,K,L)/(OMEGAciS(I,J,K,L)**2+NUen(I,J,K)**2))
      IF(ALLOCATED(DiP))  DiPS(I,J,K,L) =(KB*TiS(I,J,K,L)/MiS(L))*(NUinS(I,J,K,L)/(OMEGAciS(I,J,K,L)**2+NUinS(I,J,K,L)**2))
     END DO

     IF(ALLOCATED(OMEGAci)) OMEGAci(I,J,K)=SUM(NiS(I,J,K,:)*OMEGAciS(I,J,K,:))/SUM(NiS(I,J,K,:))
     IF(ALLOCATED(RHOi))    RHOi(I,J,K)   =SUM(NiS(I,J,K,:)*RHOiS(I,J,K,:))/SUM(NiS(I,J,K,:))
     IF(ALLOCATED(Vthi))    Vthi(I,J,K)=SUM(NiS(I,J,K,:)*VthiS(I,J,K,:))/SUM(NiS(I,J,K,:))
     IF(ALLOCATED(Cs))      Cs(I,J,K)  =SUM(NiS(I,J,K,:)*CsS(I,J,K,:))/SUM(NiS(I,J,K,:))

     IF(ALLOCATED(MUiH)) MUiH(I,J,K)=SUM(MUiHS(I,J,K,:))
     IF(ALLOCATED(MUiP)) MUiP(I,J,K)=SUM(MUiPS(I,J,K,:))
     IF(ALLOCATED(DiH))  DiH(I,J,K) =SUM( DiHS(I,J,K,:))
     IF(ALLOCATED(DiP))  DiP(I,J,K) =SUM( DiPS(I,J,K,:))

     DO L=1,NionS
      IF(ALLOCATED(SigmaO)) sigmaOS(I,J,K,L)=NiS(I,J,K,L)*(Qe**2)*((1/(Me*NUenS(I,J,K,L)))+(1/(MiS(L)*NUinS(I,J,K,L))))
      IF(ALLOCATED(SigmaH)) sigmaHS(I,J,K,L)=NiS(I,J,K,L)*(Qe**2)*((OMEGAce(I,J,K)/(Me*(OMEGAce(I,J,K)**2 &
                           &+NUenS(I,J,K,L)**2)))-(OMEGAciS(I,J,K,L)/(MiS(L)*(OMEGAciS(I,J,K,L)**2+NUinS(I,J,K,L)**2))))
      IF(ALLOCATED(SigmaP)) sigmaPS(I,J,K,L)=NiS(I,J,K,L)*(Qe**2)*((NUenS(I,J,K,L)/(Me*(OMEGAce(I,J,K)**2+NUenS(I,J,K,L)**2))) &
                           &+(NUinS(I,J,K,L)/(MiS(L)*(OMEGAciS(I,J,K,L)**2+NUinS(I,J,K,L)**2))))
     END DO

     IF(ALLOCATED(SigmaO)) sigmaO(I,J,K)=SUM(sigmaOS(I,J,K,:))
     IF(ALLOCATED(SigmaH)) sigmaH(I,J,K)=SUM(sigmaHS(I,J,K,:))
     IF(ALLOCATED(SigmaP)) sigmaP(I,J,K)=SUM(sigmaPS(I,J,K,:))

     IF(ALLOCATED(LAMBDAD)) LAMBDAD(I,J,K)=SQRT((EPSILON0*KB*Te(I,J,K))/(Ne(I,J,K)*Qe*Qe))


    END DO
   END DO
  END DO
 !$OMP END DO
 !$OMP END PARALLEL

  IF(EMPIRICAL.AND.IonoEPOTEN) THEN
   WRITE(srtDATE,"(I8)") srtDT
   IONODATAPATH="../ionoNETCDF/tiegcm"// TRIM(srtDATE) //".nc"
   INQUIRE(FILE=TRIM(IONODATAPATH),EXIST=fexist)
   IF(fexist) THEN
    CALL TIEGCMDATA(TRIM(IONODATAPATH),"POTEN",srtDT,srtLT,EPOTEN)
   ELSE
    PRINT*, "TIEGCM netCDF DATA FOR THE DATE IS NOT FOUND"
    STOP
   END IF
  END IF

  IF(IonoVion) Vion=0.0

  PRINT*, "CALCULATING SELECTED QUANTITIES >>> FINISHED"
  PRINT*, "IONOSPHERE BACKGROUND FIELDS INITIALIZATION >>> FINISHED!"

  IF(XNLOCAL.AND.YNLOCAL.AND.ZNLOCAL) THEN
   LFLDNAME="Electron Density"; LFLDUNIT="Kg/m^3"
   CALL r4r4SAVENETCDF3D("ionoBG.nc",ACCESSID,LAT1D,LON1D,ALT1D,LOCTIME,Ne,DIMSNAME,DIMSUNIT,LFLDNAME,LFLDUNIT)
   ACCESSID=ACCESSID+1
  END IF

!! DEALLOCATING NON-REQUIRED IONOSPHERE BACKGROUND PHYSICAL QUANTITIES
  IF((IonoNe .EQV..FALSE.).AND.ALLOCATED(Ne))  DEALLOCATE(Ne)
  IF((IonoNi .EQV..FALSE.).AND.ALLOCATED(Ni))  DEALLOCATE(Ni)
  IF((IonoNn .EQV..FALSE.).AND.ALLOCATED(Nn))  DEALLOCATE(Nn)
  IF((IonoTe .EQV..FALSE.).AND.ALLOCATED(Te))  DEALLOCATE(Te)
  IF((IonoTi .EQV..FALSE.).AND.ALLOCATED(Ti))  DEALLOCATE(Ti)
  IF((IonoTn .EQV..FALSE.).AND.ALLOCATED(Tn))  DEALLOCATE(Tn)
  IF((IonoNiS.EQV..FALSE.).AND.ALLOCATED(NiS)) DEALLOCATE(Nis)
  IF((IonoNnS.EQV..FALSE.).AND.ALLOCATED(NnS)) DEALLOCATE(Nns)
  IF((IonoTiS.EQV..FALSE.).AND.ALLOCATED(TiS)) DEALLOCATE(Tis)
  IF((IonoTnS.EQV..FALSE.).AND.ALLOCATED(Tns)) DEALLOCATE(Tns)

  IF((IonoBabs  .EQV..FALSE.).AND.ALLOCATED(Babs))   DEALLOCATE(Babs)
  IF((IonoBr    .EQV..FALSE.).AND.ALLOCATED(Br))     DEALLOCATE(Br)
  IF((IonoBphi  .EQV..FALSE.).AND.ALLOCATED(Bphi))   DEALLOCATE(Bphi)
  IF((IonoBtheta.EQV..FALSE.).AND.ALLOCATED(Btheta)) DEALLOCATE(Btheta)

  IF((IonoOMEGApi .EQV..FALSE.).AND.ALLOCATED(OMEGApi))  DEALLOCATE(OMEGApi)
  IF((IonoOMEGApe .EQV..FALSE.).AND.ALLOCATED(OMEGApe))  DEALLOCATE(OMEGApe)
  IF((IonoOMEGApiS.EQV..FALSE.).AND.ALLOCATED(OMEGApiS)) DEALLOCATE(OMEGApiS)
  IF((IonoOMEGAce .EQV..FALSE.).AND.ALLOCATED(OMEGAce))  DEALLOCATE(OMEGAce)
  IF((IonoOMEGAci .EQV..FALSE.).AND.ALLOCATED(OMEGAci))  DEALLOCATE(OMEGAci)
  IF((IonoOMEGAciS.EQV..FALSE.).AND.ALLOCATED(OMEGAciS)) DEALLOCATE(OMEGAciS)

  IF((IonoNUen .EQV..FALSE.).AND.ALLOCATED(NUen))  DEALLOCATE(NUen)
  IF((IonoNUin .EQV..FALSE.).AND.ALLOCATED(NUin))  DEALLOCATE(NUin)
  IF((IonoNUenS.EQV..FALSE.).AND.ALLOCATED(NUenS)) DEALLOCATE(NUenS)
  IF((IonoNUinS.EQV..FALSE.).AND.ALLOCATED(NUinS)) DEALLOCATE(NUinS)

  IF((IonoVthe .EQV..FALSE.).AND.ALLOCATED(Vthe))  DEALLOCATE(Vthe)
  IF((IonoVthi .EQV..FALSE.).AND.ALLOCATED(Vthi))  DEALLOCATE(Vthi)
  IF((IonoVthiS.EQV..FALSE.).AND.ALLOCATED(VthiS)) DEALLOCATE(VthiS)

  IF((IonoRHOe .EQV..FALSE.).AND.ALLOCATED(RHOe))  DEALLOCATE(RHOe)
  IF((IonoRHOi .EQV..FALSE.).AND.ALLOCATED(RHOi))  DEALLOCATE(RHOi)
  IF((IonoRHOiS.EQV..FALSE.).AND.ALLOCATED(RHOiS)) DEALLOCATE(RHOiS)

  IF((IonoMUeH .EQV..FALSE.).AND.ALLOCATED(MUeH))  DEALLOCATE(MUeH)
  IF((IonoMUiH .EQV..FALSE.).AND.ALLOCATED(MUiH))  DEALLOCATE(MUiH)
  IF((IonoMUiHS.EQV..FALSE.).AND.ALLOCATED(MUiHS)) DEALLOCATE(MUiHS)

  IF((IonoMUeP .EQV..FALSE.).AND.ALLOCATED(MUeP))  DEALLOCATE(MUeP)
  IF((IonoMUiP .EQV..FALSE.).AND.ALLOCATED(MUiP))  DEALLOCATE(MUiP)
  IF((IonoMUiPS.EQV..FALSE.).AND.ALLOCATED(MUiPS)) DEALLOCATE(MUiPS)

  IF((IonoDeH .EQV..FALSE.).AND.ALLOCATED(DeH))  DEALLOCATE(DeH)
  IF((IonoDiH .EQV..FALSE.).AND.ALLOCATED(DiH))  DEALLOCATE(DiH)
  IF((IonoDiHS.EQV..FALSE.).AND.ALLOCATED(DiHS)) DEALLOCATE(DiHS)

  IF((IonoDeP .EQV..FALSE.).AND.ALLOCATED(DeP))  DEALLOCATE(DeP)
  IF((IonoDiP .EQV..FALSE.).AND.ALLOCATED(DiP))  DEALLOCATE(DiP)
  IF((IonoDiPS.EQV..FALSE.).AND.ALLOCATED(DiPS)) DEALLOCATE(DiPS)

  IF((IonoSigmaO .EQV..FALSE.).AND.ALLOCATED(SigmaO))  DEALLOCATE(SigmaO)
  IF((IonoSigmaOS.EQV..FALSE.).AND.ALLOCATED(SigmaOS)) DEALLOCATE(SigmaOS)

  IF((IonoSigmaP .EQV..FALSE.).AND.ALLOCATED(SigmaP))  DEALLOCATE(SigmaP)
  IF((IonoSigmaPS.EQV..FALSE.).AND.ALLOCATED(SigmaPS)) DEALLOCATE(SigmaPS)

  IF((IonoSigmaH .EQV..FALSE.).AND.ALLOCATED(SigmaH))  DEALLOCATE(SigmaH)
  IF((IonoSigmaHS.EQV..FALSE.).AND.ALLOCATED(SigmaHS)) DEALLOCATE(SigmaHS)

  IF((IonoLne.EQV..FALSE.).AND.ALLOCATED(Lne)) DEALLOCATE(Lne)
  IF((IonoLAMBDAD.EQV..FALSE.).AND.ALLOCATED(LAMBDAD)) DEALLOCATE(LAMBDAD)

  IF((IonoEPOTEN .EQV..FALSE.).AND.ALLOCATED(EPOTEN))  DEALLOCATE(EPOTEN)
  IF((IonoEFIELD .EQV..FALSE.).AND.ALLOCATED(EFIELD))  DEALLOCATE(EFIELD)

  IF((IonoVexb .EQV..FALSE.).AND.ALLOCATED(Vexb))  DEALLOCATE(Vexb)
  IF((IonoVion .EQV..FALSE.).AND.ALLOCATED(Vion))  DEALLOCATE(Vion)
  IF((IonoVionS.EQV..FALSE.).AND.ALLOCATED(VionS)) DEALLOCATE(VionS)

  IF((IonoVzonal.EQV..FALSE.).AND.ALLOCATED(Vzonal)) DEALLOCATE(Vzonal)
  IF((IonoVmerid.EQV..FALSE.).AND.ALLOCATED(Vmerid)) DEALLOCATE(Vmerid)

  IF((IonoVAlfven .EQV..FALSE.).AND.ALLOCATED(VAlfven))  DEALLOCATE(VAlfven)
  IF((IonoVAlfvenS.EQV..FALSE.).AND.ALLOCATED(VAlfvenS)) DEALLOCATE(VAlfvenS)

  IF((IonoCs .EQV..FALSE.).AND.ALLOCATED(Cs))  DEALLOCATE(Cs)
  IF((IonoCsS.EQV..FALSE.).AND.ALLOCATED(CsS)) DEALLOCATE(CsS)

  RETURN
 END SUBROUTINE SYSBG


 SUBROUTINE RESETSYSBG()
  IMPLICIT NONE
  IF(ALLOCATED(Ne))  DEALLOCATE(Ne)
  IF(ALLOCATED(Ni))  DEALLOCATE(Ni)
  IF(ALLOCATED(Nn))  DEALLOCATE(Nn)
  IF(ALLOCATED(Te))  DEALLOCATE(Te)
  IF(ALLOCATED(Ti))  DEALLOCATE(Ti)
  IF(ALLOCATED(Tn))  DEALLOCATE(Tn)
  IF(ALLOCATED(NiS)) DEALLOCATE(Nis)
  IF(ALLOCATED(NnS)) DEALLOCATE(Nns)
  IF(ALLOCATED(TiS)) DEALLOCATE(Tis)
  IF(ALLOCATED(Tns)) DEALLOCATE(Tns)

  IF(ALLOCATED(Babs))   DEALLOCATE(Babs)
  IF(ALLOCATED(Br))     DEALLOCATE(Br)
  IF(ALLOCATED(Bphi))   DEALLOCATE(Bphi)
  IF(ALLOCATED(Btheta)) DEALLOCATE(Btheta)

  IF(ALLOCATED(OMEGApe))  DEALLOCATE(OMEGApe)
  IF(ALLOCATED(OMEGApi))  DEALLOCATE(OMEGApi)
  IF(ALLOCATED(OMEGApiS)) DEALLOCATE(OMEGApiS)
  IF(ALLOCATED(OMEGAce))  DEALLOCATE(OMEGAce)
  IF(ALLOCATED(OMEGAci))  DEALLOCATE(OMEGAci)
  IF(ALLOCATED(OMEGAciS)) DEALLOCATE(OMEGAciS)

  IF(ALLOCATED(NUen))  DEALLOCATE(NUen)
  IF(ALLOCATED(NUin))  DEALLOCATE(NUin)
  IF(ALLOCATED(NUenS)) DEALLOCATE(NUenS)
  IF(ALLOCATED(NUinS)) DEALLOCATE(NUinS)

  IF(ALLOCATED(Vthe))  DEALLOCATE(Vthe)
  IF(ALLOCATED(Vthi))  DEALLOCATE(Vthi)
  IF(ALLOCATED(VthiS)) DEALLOCATE(VthiS)

  IF(ALLOCATED(RHOe))  DEALLOCATE(RHOe)
  IF(ALLOCATED(RHOi))  DEALLOCATE(RHOi)
  IF(ALLOCATED(RHOiS)) DEALLOCATE(RHOiS)

  IF(ALLOCATED(MUeH))  DEALLOCATE(MUeH)
  IF(ALLOCATED(MUiH))  DEALLOCATE(MUiH)
  IF(ALLOCATED(MUiHS)) DEALLOCATE(MUiHS)

  IF(ALLOCATED(MUeP))  DEALLOCATE(MUeP)
  IF(ALLOCATED(MUiP))  DEALLOCATE(MUiP)
  IF(ALLOCATED(MUiPS)) DEALLOCATE(MUiPS)

  IF(ALLOCATED(DeH))  DEALLOCATE(DeH)
  IF(ALLOCATED(DiH))  DEALLOCATE(DiH)
  IF(ALLOCATED(DiHS)) DEALLOCATE(DiHS)

  IF(ALLOCATED(DeP))  DEALLOCATE(DeP)
  IF(ALLOCATED(DiP))  DEALLOCATE(DiP)
  IF(ALLOCATED(DiPS)) DEALLOCATE(DiPS)

  IF(ALLOCATED(SigmaO))  DEALLOCATE(SigmaO)
  IF(ALLOCATED(SigmaOS)) DEALLOCATE(SigmaOS)

  IF(ALLOCATED(SigmaP))  DEALLOCATE(SigmaP)
  IF(ALLOCATED(SigmaPS)) DEALLOCATE(SigmaPS)

  IF(ALLOCATED(SigmaH))  DEALLOCATE(SigmaH)
  IF(ALLOCATED(SigmaHS)) DEALLOCATE(SigmaHS)

  IF(ALLOCATED(Lne)) DEALLOCATE(Lne)
  IF(ALLOCATED(LAMBDAD)) DEALLOCATE(LAMBDAD)

  IF(ALLOCATED(EPOTEN))  DEALLOCATE(EPOTEN)
  IF(ALLOCATED(EFIELD))  DEALLOCATE(EFIELD)

  IF(ALLOCATED(Vexb))  DEALLOCATE(Vexb)
  IF(ALLOCATED(Vion))  DEALLOCATE(Vion)
  IF(ALLOCATED(VionS)) DEALLOCATE(VionS)

  IF(ALLOCATED(Vzonal)) DEALLOCATE(Vzonal)
  IF(ALLOCATED(Vmerid)) DEALLOCATE(Vmerid)

  IF(ALLOCATED(VAlfven))  DEALLOCATE(VAlfven)
  IF(ALLOCATED(VAlfvenS)) DEALLOCATE(VAlfvenS)

  IF(ALLOCATED(Cs))  DEALLOCATE(Cs)
  IF(ALLOCATED(CsS)) DEALLOCATE(CsS)

  RETURN
 END SUBROUTINE RESETSYSBG

!**************************************************************
!*** CALCULATING IONOSPHERE CARRIERS CHARGE AND TEMPERATURE ***
!**************************************************************
 SUBROUTINE IONOCARRIERS(ALT,LAT,LON,YYDDD,UTSEC,CD,CT,OTHR)
  IMPLICIT NONE

  REAL(4)          :: R,ALT,LAT,LON
  REAL(4)          :: CD(7),CT(2)
  REAL(4),OPTIONAL :: OTHR(:)
  REAL(4)          :: OUTF(20,1000),OAR(100)
  REAL(4)          :: HEIBEG,HEIEND,HEISTP
  REAL(4)          :: Hmin,Hmax,Hstp
  REAL(4)          :: UTSEC,UTHR
  INTEGER(4)       :: YYDDD,YYYY,DDD,MM,DD,MMDD,NRDAYMO
  INTEGER(4)       :: N,I,JMAG,TEMP
  LOGICAL          :: JF(50)=.FALSE.

  DDD=MOD(YYDDD,1000)
  TEMP=(YYDDD-DDD)/1000
  IF(TEMP.GE.58) THEN
    YYYY=1900+TEMP
  ELSE
    YYYY=2000+TEMP
  END IF

  UTHR=(UTSEC/3600.0)+25.0
  JMAG=0.0
  Hmin=ALT;Hmax=ALT+1.0;Hstp=1.0
  JF(2)=.TRUE.;JF(3)=.TRUE.;JF(25)=.TRUE.
  JF(8)=.TRUE.;JF(9)=.TRUE.;JF(10)=.TRUE.
  JF(11)=.TRUE.;JF(13)=.TRUE.;JF(14)=.TRUE.;JF(15)=.TRUE.
  JF(16)=.TRUE.;JF(17)=.TRUE.;JF(23)=.TRUE.;JF(24)=.TRUE.
  JF(25)=.TRUE.;JF(27)=.TRUE.;JF(28)=.TRUE.
  JF(6)=.TRUE.;JF(32)=.TRUE.

  CALL MODA(1,YYYY,MM,DD,DDD,NRDAYMO)
  MMDD=100*MM+DD

  CALL IRI_SUB(JF,JMAG,LAT,LON,YYYY,MMDD,UTHR,HMIN,HMAX,HSTP,OUTF,OAR)

  CD(1)=OUTF(1,1)
  CD(2)=OUTF(5,1)
  CD(3)=OUTF(6,1)
  CD(4)=OUTF(7,1)
  CD(5)=OUTF(8,1)
  CD(6)=OUTF(9,1)
  CD(7)=OUTF(11,1)

  CT(1)=OUTF(3,1)
  CT(2)=OUTF(4,1)

  IF(PRESENT(OTHR)) THEN
    OTHR(1)=OAR(41)  !##    F10.7 DAILY    ##!
    OTHR(2)=OAR(46)  !##   F10.7 81 DAYS   ##!
    OTHR(3)=OAR(52)  !##     AP DAILY      ##!
  END IF

 END SUBROUTINE IONOCARRIERS


!************************************************************
!*************** INTERFACE FOR TIEGCM DATA ******************
!************************************************************
 SUBROUTINE TIEGCMDATA(FNnetCDF,VARnetCDF,cDATE,cTIME,GlobalIonoVar)
  USE RDSVNETCDF
  USE INTERPSUBS
  IMPLICIT NONE
  REAL(4)                 :: tmpTIME,tmpHUR,tmpMIN,tmpSEC
  REAL(4)                 :: GlobalIonoVar(:,:,:)
  REAL(4),    ALLOCATABLE :: LocIonoVar(:,:,:,:),LocPHI3D(:,:,:),ALTZ(:,:,:,:)
  REAL(4),    ALLOCATABLE :: xLocIonoVar(:,:,:)
  REAL(4),    ALLOCATABLE :: tiegcmYEAR(:),tiegcmDAY(:),tiegcmTM(:)
  REAL(4),    ALLOCATABLE :: LocLON1D(:),LocLAT1D(:),LocALT1D(:)
  REAL(4),    ALLOCATABLE :: LocLON3D(:,:,:),LocLAT3D(:,:,:),LocALT3D(:,:,:)
  REAL(4),    ALLOCATABLE :: LocX1D(:),LocY1D(:),LocZ1D(:)
  REAL(4),    ALLOCATABLE :: LocX3D(:,:,:),LocY3D(:,:,:),LocZ3D(:,:,:)
  INTEGER(8), ALLOCATABLE :: tiegcmDTLT(:)
  INTEGER(4), ALLOCATABLE :: tiegcmTIME(:),tiegcmDATE(:)
  INTEGER(4) ,ALLOCATABLE :: VarDIMS(:)
  INTEGER(8)              :: inDTLT
  INTEGER(4)              :: MONTH,IDAY,NRDAYMO
  INTEGER(4)              :: cDATE,cTIME
  INTEGER(4)              :: iD1,ier,VarNDims,iTMSLOC
  INTEGER(4)              :: iLON,iLAT,iALT
  INTEGER(4)              :: nLAT,nLON,nALT
  INTEGER(4)              :: MATDIMS3D(3)
  CHARACTER(*)            :: FNnetCDF,VARnetCDF

  MATDIMS3D=SHAPE(GlobalIonoVar)
  nLAT=MATDIMS3D(1);nLON=MATDIMS3D(2);nALT=MATDIMS3D(3)

!TO RETRIEVE THE NAME OF ALL VARIABLES ON THE netCDF FILD
! CALL NETCDF_VAR_NAMES(TRIM(FNnetCDF))
!TIEGCM YEAR
  CALL NETCDF_VAR_NDIMS(TRIM(FNnetCDF),"year",VarNDims)
  IF(ALLOCATED(VarDIMS)) DEALLOCATE(VarDIMS)
  ALLOCATE(VarDIMS(VarNDims))
  CALL NETCDF_VAR_DIMS(TRIM(FNnetCDF),"year",VarDIMS)
  ALLOCATE(tiegcmYEAR(VarDIMS(1)))
  CALL NETCDF_VAR_GET(TRIM(FNnetCDF),"year",tiegcmYEAR)
! YEARSTPS=tiegcmYEAR(SIZE(tiegcmYEAR))-tiegcmYEAR(1)
!TIEGCM DAY
  ALLOCATE(tiegcmDAY(VarDIMS(1)))
  CALL NETCDF_VAR_GET(TRIM(FNnetCDF),"day",tiegcmDAY)
! DAYSTPS=tiegcmDAY(SIZE(tiegcmDAY))-tiegcmDAY(1)
!TIEGCM DATE
  ALLOCATE(tiegcmDATE(VarDIMS(1)))
  DO iD1=1,SIZE(tiegcmYEAR)
   CALL IDDD(1,INT(tiegcmYEAR(iD1)),MONTH,IDAY,INT(tiegcmDAY(iD1)),NRDAYMO)
   tiegcmDATE(iD1)=INT(10000*tiegcmYEAR(iD1)+100*MONTH+IDAY)
  END DO
  IF(ALLOCATED(tiegcmYEAR)) DEALLOCATE(tiegcmYEAR)
  IF(ALLOCATED(tiegcmDAY)) DEALLOCATE(tiegcmDAY)
!TIEGCM TIME
  ALLOCATE(tiegcmTM(VarDIMS(1)))
  ALLOCATE(tiegcmTIME(VarDIMS(1)))
  CALL NETCDF_VAR_GET(TRIM(FNnetCDF),"time",tiegcmTM)
  DO iD1=1,SIZE(tiegcmTM)
   tmpTIME=tiegcmTM(iD1)
   tmpHUR=INT(tiegcmTM(iD1))/60
   IF(tmpHUR.GE.24.) tmpHUR=tmpHUR-24
   tmpMIN=MOD(INT(tiegcmTM(iD1)),60)
   tmpSEC=INT((tiegcmTM(iD1)-INT(tiegcmTM(iD1)))*60.)
   tiegcmTIME(iD1)=INT(10000.*tmpHUR+100.*tmpMIN+tmpSEC)
  END DO
  IF(ALLOCATED(tiegcmTM)) DEALLOCATE(tiegcmTM)
!TIEGCM DATE-TIME
  ALLOCATE(tiegcmDTLT(VarDIMS(1)))
  tiegcmDTLT=INT8(1000000)*INT8(tiegcmDATE)+INT8(tiegcmTIME)
      inDTLT=INT8(1000000)*INT8(     cDATE)+INT8(     cTIME)
  IF(ALLOCATED(tiegcmTIME)) DEALLOCATE(tiegcmTIME)
  IF(ALLOCATED(tiegcmDATE)) DEALLOCATE(tiegcmDATE)
  IF(ANY(tiegcmDTLT.EQ.inDTLT)) THEN
   DO iD1=1,SIZE(tiegcmDTLT)
    IF(tiegcmDTLT(iD1).EQ.inDTLT) THEN
     iTMSLOC=iD1
     EXIT
    END IF
   END DO
  END IF

!TO RETIEVE THE NUMBER OF DIMENSIONS OF A VARIABLE FROM A NETCDF FILE 
!RETURN THE INTEGER(4) VarNDims
  CALL NETCDF_VAR_NDIMS(TRIM(FNnetCDF),TRIM(VARnetCDF),VarNDims)
!ALLOCATING THE VarDIMS WITH THE VarNDims OF THE VARIABLE
  IF(ALLOCATED(VarDIMS)) DEALLOCATE(VarDIMS)
  ALLOCATE(VarDIMS(VarNDims))
!print*, VarNDims
!TO RETIEVE THE LENGTH OF EACH DIMESNION OF A VARIABLE
!RETURN AN INTEGER(4) ARRAY OF NUMBER OF ELEMENTS EQUAL VarNDims
!EACH INTEGER(4) ELEMENT REPRESENT A LENGTH OF A DIMENSION OF THE VARIABLE
  CALL NETCDF_VAR_DIMS(TRIM(FNnetCDF),TRIM(VARnetCDF),VarDIMS)
!ALLOCATE THE VARIABLE ARRAY WITH THE SIZES OF EACH DIMENSION USING VarDIMS
!TO RETRIEVE THE VARIABLE DATA FROM THE NETCDF FILE
!RETURN A REAL(4) ARRAY OF DIMENSIONS THAT IS OBTAINED FROM THE VarDIMS
! ALLOCATE(LocEPOTEN(VarDIMS(1),VarDIMS(2),VarDIMS(3),VarDIMS(4)))
  ALLOCATE(LocIonoVar(VarDIMS(1),VarDIMS(2),VarDIMS(3),VarDIMS(4)))
  ALLOCATE(   ALTZ(VarDIMS(1),VarDIMS(2),VarDIMS(3),VarDIMS(4)))
! CALL NETCDF_VAR_GET(TRIM(FNnetCDF),TRIM(VARnetCDF),LocEPOTEN)
  CALL NETCDF_VAR_GET(TRIM(FNnetCDF),TRIM(VARnetCDF),LocIonoVar)
  CALL NETCDF_VAR_GET(TRIM(FNnetCDF), "Z", ALTZ)

  ALLOCATE(LocLON1D(VarDIMS(1)))
  ALLOCATE(LocLAT1D(VarDIMS(2)))
  ALLOCATE(LocALT1D(VarDIMS(3)))
  ALLOCATE(LocLON3D(VarDIMS(2),VarDIMS(1),VarDIMS(3)))
  ALLOCATE(LocLAT3D(VarDIMS(2),VarDIMS(1),VarDIMS(3)))
  ALLOCATE(LocALT3D(VarDIMS(2),VarDIMS(1),VarDIMS(3)))
  CALL NETCDF_VAR_GET(TRIM(FNnetCDF),"lon",LocLON1D)
  CALL NETCDF_VAR_GET(TRIM(FNnetCDF),"lat",LocLAT1D)
  CALL LINVECTOR(REAL(NINT(MINVAL(ALTZ))),REAL(NINT(MAXVAL(ALTZ))),VarDIMS(3),LocALT1D)
  CALL MESHGRID(LocLAT1D,LocLON1D,LocALT1D,LocLAT3D,LocLON3D,LocALT3D)
  IF(ALLOCATED(LocLAT1D)) DEALLOCATE(LocLAT1D)
  IF(ALLOCATED(LocLON1D)) DEALLOCATE(LocLON1D)

  ALLOCATE(LocX1D(nLAT))
  ALLOCATE(LocY1D(nLON))
  ALLOCATE(LocZ1D(nALT))
  ALLOCATE(LocX3D(nLAT,nLON,nALT))
  ALLOCATE(LocY3D(nLAT,nLON,nALT))
  ALLOCATE(LocZ3D(nLAT,nLON,nALT))
  CALL LINVECTOR(REAL(srtLAT),REAL(endLAT),nLAT,LocX1D)
  CALL LINVECTOR(REAL(srtLON),REAL(endLON),nLON,LocY1D)
  CALL LINVECTOR(REAL(srtALT),REAL(endALT),nALT,LocZ1D)
  CALL MESHGRID(LocX1D,LocY1D,LocZ1D,LocX3D,LocY3D,LocZ3D)
  IF(ALLOCATED(LocX1D)) DEALLOCATE(LocX1D)
  IF(ALLOCATED(LocY1D)) DEALLOCATE(LocY1D)
  IF(ALLOCATED(LocZ1D)) DEALLOCATE(LocZ1D)

! ALLOCATE(xEPOTEN(VarDIMS(1),VarDIMS(2),VarDIMS(3)))
! call glbhtin(LocEPOTEN(:,:,:,iTMSLOC),ALTZ(:,:,:,iTMSLOC),VarDIMS(1),VarDIMS(2),VarDIMS(3),xEPOTEN,LocALT1D,VarDIMS(3),0,0.,ier,1)
  ALLOCATE(xLocIonoVar(VarDIMS(1),VarDIMS(2),VarDIMS(3)))
  call glbhtin(LocIonoVar(:,:,:,iTMSLOC),ALTZ(:,:,:,iTMSLOC),VarDIMS(1),VarDIMS(2),VarDIMS(3), &
              &xLocIonoVar,LocALT1D,VarDIMS(3),0,0.,ier,1)
  IF(ALLOCATED(ALTZ)) DEALLOCATE(ALTZ)
! IF(ALLOCATED(LocEPOTEN)) DEALLOCATE(LocEPOTEN)
  IF(ALLOCATED(LocIonoVar)) DEALLOCATE(LocIonoVar)
  ALLOCATE(LocPHI3D(VarDIMS(2),VarDIMS(1),VarDIMS(3)))
! DO iALT=1,VarDIMS(3)
!  LocPHI3D(:,:,iALT)=TRANSPOSE(xEPOTEN(:,:,iALT))
! END DO
! IF(ALLOCATED(xEPOTEN)) DEALLOCATE(xEPOTEN)
! CALL QSHEPFIT(LocLAT3D,LocLON3D,LocALT3D/100000.,LocPHI3D,LocX3D,LocY3D,LocZ3D,EPOTEN)
  DO iALT=1,VarDIMS(3)
   LocPHI3D(:,:,iALT)=TRANSPOSE(xLocIonoVar(:,:,iALT))
  END DO
  IF(ALLOCATED(xLocIonoVar)) DEALLOCATE(xLocIonoVar)
  CALL QSHEPFIT(LocLAT3D,LocLON3D,LocALT3D/100000.,LocPHI3D,LocX3D,LocY3D,LocZ3D,GlobalIonoVar)

  RETURN
 END SUBROUTINE TIEGCMDATA


!************************************************************
!*********** GEOMAGNETIC DIPOLE FIELD COMPONENTS ************
!************************************************************
SUBROUTINE R4GEOBFIELD(GeoAxes,RG,THETAG,PHIG,IGRFYEAR,H,Hx,Hy,Hz,Hxy,Hdip,Hvar)
  IMPLICIT NONE
  REAL(4) :: RG,R3
  REAL(4) :: THETAG,PHIG,THETACD,PHICD,PSI
  REAL(4) :: IGRFYEAR
  REAL(4) :: H,Hx,Hy,Hz
  REAL(4), OPTIONAL :: Hxy,Hdip,Hvar
  CHARACTER*2 :: GeoAxes

  IF(TRIM(GeoAxes).EQ."CD") THEN
    IF(PRESENT(Hxy).AND.PRESENT(Hdip).AND.PRESENT(Hvar)) THEN
        CALL CDBFIELD(RG,THETAG,PHIG,IGRFYEAR,H,Hx,Hy,Hz,Hxy,Hdip,Hvar)
    ELSE IF(PRESENT(Hxy).AND.PRESENT(Hdip)) THEN
        CALL CDBFIELD(RG,THETAG,PHIG,IGRFYEAR,H,Hx,Hy,Hz,Hxy,Hdip)
    ELSE IF(PRESENT(Hxy)) THEN
        CALL CDBFIELD(RG,THETAG,PHIG,IGRFYEAR,H,Hx,Hy,Hz,Hxy)
    ELSE
        CALL CDBFIELD(RG,THETAG,PHIG,IGRFYEAR,H,Hx,Hy,Hz)
    END IF
  ELSE IF(TRIM(GeoAxes).EQ."ED") THEN
    IF(PRESENT(Hxy).AND.PRESENT(Hdip).AND.PRESENT(Hvar)) THEN
        CALL EDBFIELD(RG,THETAG,PHIG,IGRFYEAR,H,Hx,Hy,Hz,Hxy,Hdip,Hvar)
    ELSE IF(PRESENT(Hxy).AND.PRESENT(Hdip)) THEN
        CALL EDBFIELD(RG,THETAG,PHIG,IGRFYEAR,H,Hx,Hy,Hz,Hxy,Hdip)
    ELSE IF(PRESENT(Hxy)) THEN
        CALL EDBFIELD(RG,THETAG,PHIG,IGRFYEAR,H,Hx,Hy,Hz,Hxy)
    ELSE
        CALL EDBFIELD(RG,THETAG,PHIG,IGRFYEAR,H,Hx,Hy,Hz)
    END IF
  END IF
 END SUBROUTINE R4GEOBFIELD

 SUBROUTINE R8GEOBFIELD(GeoAxes,RG,THETAG,PHIG,IGRFYEAR,H,Hx,Hy,Hz,Hxy,Hdip,Hvar)
  IMPLICIT NONE
  REAL(8) :: RG,R3
  REAL(8) :: THETAG,PHIG,THETACD,PHICD,PSI
  REAL(8) :: IGRFYEAR
  REAL(8) :: H,Hx,Hy,Hz
  REAL(8), OPTIONAL :: Hxy,Hdip,Hvar
  CHARACTER*2 :: GeoAxes

  IF(TRIM(GeoAxes).EQ."CD") THEN
    IF(PRESENT(Hxy).AND.PRESENT(Hdip).AND.PRESENT(Hvar)) THEN
        CALL CDBFIELD(RG,THETAG,PHIG,IGRFYEAR,H,Hx,Hy,Hz,Hxy,Hdip,Hvar)
    ELSE IF(PRESENT(Hxy).AND.PRESENT(Hdip)) THEN
        CALL CDBFIELD(RG,THETAG,PHIG,IGRFYEAR,H,Hx,Hy,Hz,Hxy,Hdip)
    ELSE IF(PRESENT(Hxy)) THEN
        CALL CDBFIELD(RG,THETAG,PHIG,IGRFYEAR,H,Hx,Hy,Hz,Hxy)
    ELSE
        CALL CDBFIELD(RG,THETAG,PHIG,IGRFYEAR,H,Hx,Hy,Hz)
    END IF
  ELSE IF(TRIM(GeoAxes).EQ."ED") THEN
    IF(PRESENT(Hxy).AND.PRESENT(Hdip).AND.PRESENT(Hvar)) THEN
        CALL EDBFIELD(RG,THETAG,PHIG,IGRFYEAR,H,Hx,Hy,Hz,Hxy,Hdip,Hvar)
    ELSE IF(PRESENT(Hxy).AND.PRESENT(Hdip)) THEN
        CALL EDBFIELD(RG,THETAG,PHIG,IGRFYEAR,H,Hx,Hy,Hz,Hxy,Hdip)
    ELSE IF(PRESENT(Hxy)) THEN
        CALL EDBFIELD(RG,THETAG,PHIG,IGRFYEAR,H,Hx,Hy,Hz,Hxy)
    ELSE
        CALL EDBFIELD(RG,THETAG,PHIG,IGRFYEAR,H,Hx,Hy,Hz)
    END IF
  END IF
 END SUBROUTINE R8GEOBFIELD

!**********************************************************
!****** GEOCENTRIC DIPOLE MAGENTIC FIELD COMPONENTS *******
!**********************************************************
 SUBROUTINE R4CDBFIELD(RG,THETAG,PHIG,IGRFYEAR,H,Hx,Hy,Hz,Hxy,Hdip,Hvar)
  IMPLICIT NONE
  REAL(4) :: RG,R3
  REAL(4) :: THETAG,PHIG,THETACD,PHICD,PSI
  REAL(4) :: Bo,Btot,Br,Btheta,Bphi,Bthetacd
  REAL(4) :: IGRFYEAR
  REAL(4) :: H,Hx,Hy,Hz
  REAL(4), OPTIONAL :: Hxy,Hdip,Hvar
  REAL(4),PARAMETER :: RE=6378.1

  CALL GEO2CD(THETAG,PHIG,THETACD,PHICD,IGRFYEAR,PSI)

  CALL IGRF(IGRFYEAR,Bo)    ! GIVES THE MAGNETIC FIELD IN (nT)
  Bo=1.0e-9*Bo              ! TO CONVERT FROM (nT) TO (T)
  R3=(RE/RG)*(RE/RG)*(RE/RG)

  Btot=Bo*SQRT(3.0*COS(THETACD)*COS(THETACD)+1.0)*R3
  Br=-2.0*Bo*COS(THETACD)*R3
  Bthetacd=-Bo*SIN(THETACD)*R3

  Btheta=Bthetacd*COS(PSI)
  Bphi=Bthetacd*SIN(PSI)
  IF(ABS(Bphi).LT.1.0e-15) Bphi=0.0e0
  IF(ABS(Btheta).LT.1.0e-15) Btheta=0.0e0

  H=ABS(Btot)
  Hx=-Btheta
  Hy=Bphi
  Hz=-Br

  IF(PRESENT(Hxy))  Hxy =ABS(Bthetacd)
  IF(PRESENT(Hdip)) Hdip=ATAN(Br/Bthetacd)
  IF(PRESENT(Hvar)) Hvar=PSI

 END SUBROUTINE R4CDBFIELD

 SUBROUTINE R8CDBFIELD(RG,THETAG,PHIG,IGRFYEAR,H,Hx,Hy,Hz,Hxy,Hdip,Hvar)
  IMPLICIT NONE
  REAL(8) :: RG,R3
  REAL(8) :: THETAG,PHIG,THETACD,PHICD,PSI
  REAL(8) :: Bo,Btot,Br,Btheta,Bphi,Bthetacd
  REAL(8) :: IGRFYEAR
  REAL(8) :: H,Hx,Hy,Hz
  REAL(8), OPTIONAL :: Hxy,Hdip,Hvar
  REAL(8),PARAMETER :: RE=6378.1

  CALL GEO2CD(THETAG,PHIG,THETACD,PHICD,IGRFYEAR,PSI)

  CALL IGRF(IGRFYEAR,Bo)    ! GIVES THE MAGNETIC FIELD IN (nT)
  Bo=1.0d-9*Bo              ! TO CONVERT FROM (nT) TO (T)
  R3=(RE/RG)*(RE/RG)*(RE/RG)

  Btot=Bo*SQRT(3.0*COS(THETACD)*COS(THETACD)+1.0)*R3
  Br=-2.0*Bo*COS(THETACD)*R3
  Bthetacd=-Bo*SIN(THETACD)*R3

  Btheta=Bthetacd*COS(PSI)
  Bphi=Bthetacd*SIN(PSI)
  IF(ABS(Bphi).LT.1.0d-15) Bphi=0.0d0
  IF(ABS(Btheta).LT.1.0d-15) Btheta=0.0d0

  H=ABS(Btot)
  Hx=-Btheta
  Hy=Bphi
  Hz=-Br

  IF(PRESENT(Hxy))  Hxy =ABS(Bthetacd)
  IF(PRESENT(Hdip)) Hdip=ATAN(Br/Bthetacd)
  IF(PRESENT(Hvar)) Hvar=PSI

 END SUBROUTINE R8CDBFIELD

!**********************************************************
!****** ECCENTRIC DIPOLE MAGENTIC FIELD COMPONENTS ********
!**********************************************************
 SUBROUTINE R4EDBFIELD(RG,THETAG,PHIG,IGRFYEAR,H,Hx,Hy,Hz,Hxy,Hdip,Hvar)
  IMPLICIT NONE
  REAL(4) :: RG,RED,R3
  REAL(4) :: THETAG,PHIG,THETACD,PHICD,THETAED,PHIED,PSI
  REAL(4) :: MBo,Bo,Btot,Btheta,Bphi,Bred,Bthetaed
  REAL(4) :: IGRFYEAR
  REAL(4) :: H,Hx,Hy,Hz
  REAL(4), OPTIONAL :: Hdip,Hvar,Hxy
  REAL(4) :: THETAN,PHIN,COSPSI,SINPSI
  REAL(4),PARAMETER :: PI=4.0*ATAN(1.0)
  REAL(4),PARAMETER :: MU0=4.0e-7*PI
  REAL(4),PARAMETER :: RE=6378.1

  CALL GEO2CD(THETAG,PHIG,THETACD,PHICD,IGRFYEAR,PSI)
  CALL CD2ED(RG,THETACD,PHICD,RED,THETAED,PHIED,IGRFYEAR)
  THETAED=PI/2-THETAED
  IF(PHIED.GT.PI) PHIED=PHIED+2.0*PI

  CALL IGRF(IGRFYEAR,Bo,THETAN,PHIN)    ! GIVES THE MAGNETIC FIELD IN (nT)
  THETAN=PI/2-THETAN
  IF(PHIN.LT.0) PHIN=PHIN+2.0*PI

  Bo=1.0e-9*Bo              ! TO CONVERT FROM (nT) TO (T)
  R3=(RE/RED)*(RE/RED)*(RE/RED)
  MBo=(4.0*PI/MU0)*Bo*(RE**3)

  Btot=Bo*SQRT(3.0*COS(THETAED)*COS(THETAED)+1.0)*R3
  Bred=-2.0*Bo*COS(THETAED)*R3
  Bthetaed=-Bo*SIN(THETAED)*R3

! Btheta= Bthetaed*COS(PSI)
! Bphi  =-Bthetaed*SIN(PSI)
! IF(ABS(Bphi).LT.1.0e-15) Bphi=0.0e0
! IF(ABS(Btheta).LT.1.0e-15) Btheta=0.0e0

  COSPSI=(COS(THETAN)-COS(THETAG)*COS(THETACD))/(SIN(THETAG)*SIN(THETACD))
  SINPSI=(-SIN(PHIN)*SIN(PHIG-PHIN))/SIN(THETACD)
  Btheta= Bthetaed*COSPSI
  Bphi  =-Bthetaed*SINPSI

  H   =ABS(Btot)
  Hx  =-Btheta
  Hy  = Bphi
  Hz  =-Bred

  IF(PRESENT(Hxy))  Hxy =ABS(Bthetaed)
  IF(PRESENT(Hdip)) Hdip=ATAN2(Bred,Bthetaed)
  IF(PRESENT(Hvar)) Hvar=PSI

 END SUBROUTINE R4EDBFIELD


 SUBROUTINE R8EDBFIELD(RG,THETAG,PHIG,IGRFYEAR,H,Hx,Hy,Hz,Hxy,Hdip,Hvar)
  IMPLICIT NONE
  REAL(8) :: RG,RED,R3
  REAL(8) :: THETAG,PHIG,THETACD,PHICD,THETAED,PHIED,PSI
  REAL(8) :: MBo,Bo,Btot,Btheta,Bphi,Bred,Bthetaed
  REAL(8) :: IGRFYEAR
  REAL(8) :: H,Hx,Hy,Hz
  REAL(8), OPTIONAL :: Hdip,Hvar,Hxy
  REAL(8) :: THETAN,PHIN,COSPSI,SINPSI
  REAL(8),PARAMETER :: PI=4.0d0*ATAN(1.0d0)
  REAL(8),PARAMETER :: MU0=4.0E-7*PI
  REAL(8),PARAMETER :: RE=6378.1

  CALL GEO2CD(THETAG,PHIG,THETACD,PHICD,IGRFYEAR,PSI)
  CALL CD2ED(RG,THETACD,PHICD,RED,THETAED,PHIED,IGRFYEAR)

  CALL IGRF(IGRFYEAR,Bo,THETAN,PHIN)    ! GIVES THE MAGNETIC FIELD IN (nT)
  Bo=1.0d-9*Bo              ! TO CONVERT FROM (nT) TO (T)
  R3=(RE/RED)*(RE/RED)*(RE/RED)
  MBo=(4.0*PI/MU0)*Bo*(RE**3)

  Btot=Bo*SQRT(3.0*COS(THETAED)*COS(THETAED)+1.0)*R3
  Bred=-2.0*Bo*COS(THETAED)*R3
  Bthetaed=-Bo*SIN(THETAED)*R3

! Btheta= Bthetaed*COS(PSI)
! Bphi  =-Bthetaed*SIN(PSI)

  COSPSI=(COS(THETAN)-COS(THETAG)*COS(THETACD))/(SIN(THETAG)*SIN(THETACD))
  SINPSI=(-SIN(PHIN)*SIN(PHIG-PHIN))/SIN(THETACD)
  Btheta= Bthetaed*COSPSI
  Bphi  =-Bthetaed*SINPSI

  H   =ABS(Btot)
  Hx  =-Btheta
  Hy  = Bphi
  Hz  =-Bred

  IF(PRESENT(Hxy))  Hxy =ABS(Bthetaed)
  IF(PRESENT(Hdip)) Hdip=ATAN(Bred/Bthetaed)
  IF(PRESENT(Hvar)) Hvar=PSI

 END SUBROUTINE R8EDBFIELD



END MODULE IONOBG
